#!/bin/bash
# REV08: Mon 18 Nov 2024 09:00
# REV07: Thu  1 Mar 2018 21:00
# START: Mon  5 Sep 2016 11:00

# These are some command lines 
# Copyright (C) 2016-2024 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

XX="xx"
clear
echo ""; echo "This is a SYSTEMD - systemctl demo."
echo "Just run: \"bash $0\""
echo ""; echo "*** Hit Enter Key ***";
[ "$1" = "$XX" ] || (read YY ; clear)

for II in      \
    'systemctl list-unit-files | head -8; echo "(...)";systemctl list-unit-files| tail -8' \
    'systemd-analyze blame | wc -l; echo "===";systemd-analyze blame | head -10' \
    'systemctl --full  | wc -l; echo "===";systemctl --full  | head -6' \
    'systemctl list-units  | wc -l; echo "===";systemctl list-units | head -6' \
    'systemctl list-units |grep .service|wc -l;echo "===";systemctl list-units|grep .service|head -6' \
    'systemctl list-units  | grep ssh.service' \
    'systemctl status ssh.service' \
    'systemctl is-enabled ssh' \

do
    COMMENT="RUNNING:  $II"
    SIZE=${#COMMENT}
    (( $SIZE > 80 )) && SIZE=80
    STR=$(eval printf "%0.s=" {1..$SIZE})
    echo "$STR"
    echo $COMMENT
    echo "$STR"
    eval $II
    echo ""; echo "*** Hit Enter Key ***";
    [ "$1" = "$XX" ] || (read YY ; clear)
done

exit

# INFO: systemctl list-unit-files
# INFO: This command helps administrators keep track of what units are configured to start automatically or manually.
# INFO: UNIT FILE: The name of the unit file 
# INFO: STATE: The status of the unit
# INFO: == enabled: The unit is set to start automatically at boot.
# INFO: == disabled: The unit is not set to start automatically.
# INFO: == static: The unit is not enabled by default, but it can be started by another unit.
# INFO: == masked: The unit is deliberately disabled, and it cannot be started manually or automatically.
# INFO: 
# INFO: systemctl list-units
# INFO: shows information about units such as services, targets, mount points, devices, and more.
# INFO: UNIT: The name of the unit (e.g., nginx.service).
# INFO: LOAD: Indicates whether the unit is loaded into memory.
# INFO: ACTIVE: The current status of the unit (e.g., active, inactive).
# INFO: == active: The unit is currently running or has completed its work (for ones that exit after running).
# INFO: == inactive: The unit is not currently running.
# INFO: == failed: The unit has failed to start or encountered an error.
# INFO: == activating: The unit is in the process of starting up.
# INFO: == deactivating: The unit is in the process of stopping.
# INFO: SUB: A more specific status of the unit (e.g., running, exited).
# INFO: DESCRIPTION: A brief description of the unit's function.
# INFO: 
# INFO: EXAMPLES:
# INFO: systemctl start nginx.service
# INFO: systemctl stop nginx.service
# INFO: systemctl restart nginx.service
# INFO: systemctl enable nginx.service
# INFO: systemctl disable nginx.service
# INFO: systemctl mask nginx.service
# INFO: systemctl unmask nginx.service
# INFO: journalctl -u nginx.service
# INFO: journalctl -b
# INFO: journalctl --since "1 hour ago"
# INFO: journalctl -f
# INFO: systemctl show nginx.service
# INFO: systemctl list-units --type=target
# INFO:
# INFO:

